# Generated by Django 3.0.8 on 2020-07-06 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Act',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=200)),
                ('tz', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(default=datetime.date.today, verbose_name='Date')),
                ('end_time', models.DateTimeField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
    ]
